fragment SettingsParts on Settings {
  __typename
  siteName
  siteTagline
  logoText
  logoImage
  navLinks {
    __typename
    label
    href
  }
  navCtaLabel
  navCtaLink
  footerTagline
  footerLinks {
    __typename
    label
    href
  }
  copyrightText
  googleFontsUrl
  socialLinks {
    __typename
    platform
    url
  }
}

fragment HomeParts on Home {
  __typename
  title
  hero {
    __typename
    tagline
    ctaPrimary
    ctaSecondary
    backgroundImage
  }
  about {
    __typename
    headline
    story
    image
  }
  menu {
    __typename
    headline
    items {
      __typename
      name
      description
      image
    }
  }
  experience {
    __typename
    headline
    description
    gallery
  }
  testimonials {
    __typename
    headline
    list {
      __typename
      quote
      author
    }
  }
  location {
    __typename
    headline
    address
    hours
    whatsappNumber
  }
}
