//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  settings: Settings;
  settingsConnection: SettingsConnection;
  home: Home;
  homeConnection: HomeConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};

export type DocumentFilter = {
  settings?: InputMaybe<SettingsFilter>;
  home?: InputMaybe<HomeFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Settings | Home | Folder;

export type SettingsNavLinks = {
  __typename?: 'SettingsNavLinks';
  label: Scalars['String']['output'];
  href: Scalars['String']['output'];
};

export type SettingsFooterLinks = {
  __typename?: 'SettingsFooterLinks';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type SettingsSocialLinks = {
  __typename?: 'SettingsSocialLinks';
  platform?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type Settings = Node & Document & {
  __typename?: 'Settings';
  siteName: Scalars['String']['output'];
  siteTagline?: Maybe<Scalars['String']['output']>;
  logoText?: Maybe<Scalars['String']['output']>;
  logoImage?: Maybe<Scalars['String']['output']>;
  navLinks?: Maybe<Array<Maybe<SettingsNavLinks>>>;
  navCtaLabel?: Maybe<Scalars['String']['output']>;
  navCtaLink?: Maybe<Scalars['String']['output']>;
  footerTagline?: Maybe<Scalars['String']['output']>;
  footerLinks?: Maybe<Array<Maybe<SettingsFooterLinks>>>;
  copyrightText?: Maybe<Scalars['String']['output']>;
  googleFontsUrl?: Maybe<Scalars['String']['output']>;
  socialLinks?: Maybe<Array<Maybe<SettingsSocialLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SettingsNavLinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type SettingsFooterLinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type SettingsSocialLinksFilter = {
  platform?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type SettingsFilter = {
  siteName?: InputMaybe<StringFilter>;
  siteTagline?: InputMaybe<StringFilter>;
  logoText?: InputMaybe<StringFilter>;
  logoImage?: InputMaybe<ImageFilter>;
  navLinks?: InputMaybe<SettingsNavLinksFilter>;
  navCtaLabel?: InputMaybe<StringFilter>;
  navCtaLink?: InputMaybe<StringFilter>;
  footerTagline?: InputMaybe<StringFilter>;
  footerLinks?: InputMaybe<SettingsFooterLinksFilter>;
  copyrightText?: InputMaybe<StringFilter>;
  googleFontsUrl?: InputMaybe<StringFilter>;
  socialLinks?: InputMaybe<SettingsSocialLinksFilter>;
};

export type SettingsConnectionEdges = {
  __typename?: 'SettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Settings>;
};

export type SettingsConnection = Connection & {
  __typename?: 'SettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SettingsConnectionEdges>>>;
};

export type HomeHero = {
  __typename?: 'HomeHero';
  tagline?: Maybe<Scalars['String']['output']>;
  ctaPrimary?: Maybe<Scalars['String']['output']>;
  ctaSecondary?: Maybe<Scalars['String']['output']>;
  backgroundImage?: Maybe<Scalars['String']['output']>;
};

export type HomeAbout = {
  __typename?: 'HomeAbout';
  headline?: Maybe<Scalars['String']['output']>;
  story?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type HomeMenuItems = {
  __typename?: 'HomeMenuItems';
  name?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type HomeMenu = {
  __typename?: 'HomeMenu';
  headline?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<HomeMenuItems>>>;
};

export type HomeExperience = {
  __typename?: 'HomeExperience';
  headline?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  gallery?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type HomeTestimonialsList = {
  __typename?: 'HomeTestimonialsList';
  quote?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
};

export type HomeTestimonials = {
  __typename?: 'HomeTestimonials';
  headline?: Maybe<Scalars['String']['output']>;
  list?: Maybe<Array<Maybe<HomeTestimonialsList>>>;
};

export type HomeLocation = {
  __typename?: 'HomeLocation';
  headline?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  hours?: Maybe<Scalars['String']['output']>;
  whatsappNumber?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  title: Scalars['String']['output'];
  hero?: Maybe<HomeHero>;
  about?: Maybe<HomeAbout>;
  menu?: Maybe<HomeMenu>;
  experience?: Maybe<HomeExperience>;
  testimonials?: Maybe<HomeTestimonials>;
  location?: Maybe<HomeLocation>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomeHeroFilter = {
  tagline?: InputMaybe<StringFilter>;
  ctaPrimary?: InputMaybe<StringFilter>;
  ctaSecondary?: InputMaybe<StringFilter>;
  backgroundImage?: InputMaybe<ImageFilter>;
};

export type HomeAboutFilter = {
  headline?: InputMaybe<StringFilter>;
  story?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type HomeMenuItemsFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type HomeMenuFilter = {
  headline?: InputMaybe<StringFilter>;
  items?: InputMaybe<HomeMenuItemsFilter>;
};

export type HomeExperienceFilter = {
  headline?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  gallery?: InputMaybe<ImageFilter>;
};

export type HomeTestimonialsListFilter = {
  quote?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
};

export type HomeTestimonialsFilter = {
  headline?: InputMaybe<StringFilter>;
  list?: InputMaybe<HomeTestimonialsListFilter>;
};

export type HomeLocationFilter = {
  headline?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  hours?: InputMaybe<StringFilter>;
  whatsappNumber?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  title?: InputMaybe<StringFilter>;
  hero?: InputMaybe<HomeHeroFilter>;
  about?: InputMaybe<HomeAboutFilter>;
  menu?: InputMaybe<HomeMenuFilter>;
  experience?: InputMaybe<HomeExperienceFilter>;
  testimonials?: InputMaybe<HomeTestimonialsFilter>;
  location?: InputMaybe<HomeLocationFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSettings: Settings;
  createSettings: Settings;
  updateHome: Home;
  createHome: Home;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationCreateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};

export type DocumentUpdateMutation = {
  settings?: InputMaybe<SettingsMutation>;
  home?: InputMaybe<HomeMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  settings?: InputMaybe<SettingsMutation>;
  home?: InputMaybe<HomeMutation>;
};

export type SettingsNavLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsFooterLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsSocialLinksMutation = {
  platform?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsMutation = {
  siteName?: InputMaybe<Scalars['String']['input']>;
  siteTagline?: InputMaybe<Scalars['String']['input']>;
  logoText?: InputMaybe<Scalars['String']['input']>;
  logoImage?: InputMaybe<Scalars['String']['input']>;
  navLinks?: InputMaybe<Array<InputMaybe<SettingsNavLinksMutation>>>;
  navCtaLabel?: InputMaybe<Scalars['String']['input']>;
  navCtaLink?: InputMaybe<Scalars['String']['input']>;
  footerTagline?: InputMaybe<Scalars['String']['input']>;
  footerLinks?: InputMaybe<Array<InputMaybe<SettingsFooterLinksMutation>>>;
  copyrightText?: InputMaybe<Scalars['String']['input']>;
  googleFontsUrl?: InputMaybe<Scalars['String']['input']>;
  socialLinks?: InputMaybe<Array<InputMaybe<SettingsSocialLinksMutation>>>;
};

export type HomeHeroMutation = {
  tagline?: InputMaybe<Scalars['String']['input']>;
  ctaPrimary?: InputMaybe<Scalars['String']['input']>;
  ctaSecondary?: InputMaybe<Scalars['String']['input']>;
  backgroundImage?: InputMaybe<Scalars['String']['input']>;
};

export type HomeAboutMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  story?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMenuItemsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMenuMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<HomeMenuItemsMutation>>>;
};

export type HomeExperienceMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  gallery?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeTestimonialsListMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
};

export type HomeTestimonialsMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  list?: InputMaybe<Array<InputMaybe<HomeTestimonialsListMutation>>>;
};

export type HomeLocationMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  hours?: InputMaybe<Scalars['String']['input']>;
  whatsappNumber?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  hero?: InputMaybe<HomeHeroMutation>;
  about?: InputMaybe<HomeAboutMutation>;
  menu?: InputMaybe<HomeMenuMutation>;
  experience?: InputMaybe<HomeExperienceMutation>;
  testimonials?: InputMaybe<HomeTestimonialsMutation>;
  location?: InputMaybe<HomeLocationMutation>;
};

export type SettingsPartsFragment = { __typename: 'Settings', siteName: string, siteTagline?: string | null, logoText?: string | null, logoImage?: string | null, navCtaLabel?: string | null, navCtaLink?: string | null, footerTagline?: string | null, copyrightText?: string | null, googleFontsUrl?: string | null, navLinks?: Array<{ __typename: 'SettingsNavLinks', label: string, href: string } | null> | null, footerLinks?: Array<{ __typename: 'SettingsFooterLinks', label?: string | null, href?: string | null } | null> | null, socialLinks?: Array<{ __typename: 'SettingsSocialLinks', platform?: string | null, url?: string | null } | null> | null };

export type HomePartsFragment = { __typename: 'Home', title: string, hero?: { __typename: 'HomeHero', tagline?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null, backgroundImage?: string | null } | null, about?: { __typename: 'HomeAbout', headline?: string | null, story?: string | null, image?: string | null } | null, menu?: { __typename: 'HomeMenu', headline?: string | null, items?: Array<{ __typename: 'HomeMenuItems', name?: string | null, description?: string | null, image?: string | null } | null> | null } | null, experience?: { __typename: 'HomeExperience', headline?: string | null, description?: string | null, gallery?: Array<string | null> | null } | null, testimonials?: { __typename: 'HomeTestimonials', headline?: string | null, list?: Array<{ __typename: 'HomeTestimonialsList', quote?: string | null, author?: string | null } | null> | null } | null, location?: { __typename: 'HomeLocation', headline?: string | null, address?: string | null, hours?: string | null, whatsappNumber?: string | null } | null };

export type SettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SettingsQuery = { __typename?: 'Query', settings: { __typename: 'Settings', id: string, siteName: string, siteTagline?: string | null, logoText?: string | null, logoImage?: string | null, navCtaLabel?: string | null, navCtaLink?: string | null, footerTagline?: string | null, copyrightText?: string | null, googleFontsUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navLinks?: Array<{ __typename: 'SettingsNavLinks', label: string, href: string } | null> | null, footerLinks?: Array<{ __typename: 'SettingsFooterLinks', label?: string | null, href?: string | null } | null> | null, socialLinks?: Array<{ __typename: 'SettingsSocialLinks', platform?: string | null, url?: string | null } | null> | null } };

export type SettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
}>;


export type SettingsConnectionQuery = { __typename?: 'Query', settingsConnection: { __typename?: 'SettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SettingsConnectionEdges', cursor: string, node?: { __typename: 'Settings', id: string, siteName: string, siteTagline?: string | null, logoText?: string | null, logoImage?: string | null, navCtaLabel?: string | null, navCtaLink?: string | null, footerTagline?: string | null, copyrightText?: string | null, googleFontsUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navLinks?: Array<{ __typename: 'SettingsNavLinks', label: string, href: string } | null> | null, footerLinks?: Array<{ __typename: 'SettingsFooterLinks', label?: string | null, href?: string | null } | null> | null, socialLinks?: Array<{ __typename: 'SettingsSocialLinks', platform?: string | null, url?: string | null } | null> | null } | null } | null> | null } };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, title: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', tagline?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null, backgroundImage?: string | null } | null, about?: { __typename: 'HomeAbout', headline?: string | null, story?: string | null, image?: string | null } | null, menu?: { __typename: 'HomeMenu', headline?: string | null, items?: Array<{ __typename: 'HomeMenuItems', name?: string | null, description?: string | null, image?: string | null } | null> | null } | null, experience?: { __typename: 'HomeExperience', headline?: string | null, description?: string | null, gallery?: Array<string | null> | null } | null, testimonials?: { __typename: 'HomeTestimonials', headline?: string | null, list?: Array<{ __typename: 'HomeTestimonialsList', quote?: string | null, author?: string | null } | null> | null } | null, location?: { __typename: 'HomeLocation', headline?: string | null, address?: string | null, hours?: string | null, whatsappNumber?: string | null } | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, title: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', tagline?: string | null, ctaPrimary?: string | null, ctaSecondary?: string | null, backgroundImage?: string | null } | null, about?: { __typename: 'HomeAbout', headline?: string | null, story?: string | null, image?: string | null } | null, menu?: { __typename: 'HomeMenu', headline?: string | null, items?: Array<{ __typename: 'HomeMenuItems', name?: string | null, description?: string | null, image?: string | null } | null> | null } | null, experience?: { __typename: 'HomeExperience', headline?: string | null, description?: string | null, gallery?: Array<string | null> | null } | null, testimonials?: { __typename: 'HomeTestimonials', headline?: string | null, list?: Array<{ __typename: 'HomeTestimonialsList', quote?: string | null, author?: string | null } | null> | null } | null, location?: { __typename: 'HomeLocation', headline?: string | null, address?: string | null, hours?: string | null, whatsappNumber?: string | null } | null } | null } | null> | null } };

export const SettingsPartsFragmentDoc = gql`
    fragment SettingsParts on Settings {
  __typename
  siteName
  siteTagline
  logoText
  logoImage
  navLinks {
    __typename
    label
    href
  }
  navCtaLabel
  navCtaLink
  footerTagline
  footerLinks {
    __typename
    label
    href
  }
  copyrightText
  googleFontsUrl
  socialLinks {
    __typename
    platform
    url
  }
}
    `;
export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  title
  hero {
    __typename
    tagline
    ctaPrimary
    ctaSecondary
    backgroundImage
  }
  about {
    __typename
    headline
    story
    image
  }
  menu {
    __typename
    headline
    items {
      __typename
      name
      description
      image
    }
  }
  experience {
    __typename
    headline
    description
    gallery
  }
  testimonials {
    __typename
    headline
    list {
      __typename
      quote
      author
    }
  }
  location {
    __typename
    headline
    address
    hours
    whatsappNumber
  }
}
    `;
export const SettingsDocument = gql`
    query settings($relativePath: String!) {
  settings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SettingsParts
  }
}
    ${SettingsPartsFragmentDoc}`;
export const SettingsConnectionDocument = gql`
    query settingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SettingsFilter) {
  settingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SettingsParts
      }
    }
  }
}
    ${SettingsPartsFragmentDoc}`;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      settings(variables: SettingsQueryVariables, options?: C): Promise<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}> {
        return requester<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}, SettingsQueryVariables>(SettingsDocument, variables, options);
      },
    settingsConnection(variables?: SettingsConnectionQueryVariables, options?: C): Promise<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}, SettingsConnectionQueryVariables>(SettingsConnectionDocument, variables, options);
      },
    home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  